
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.yandex.ru
          server_port: 465
          username: 25101983@tut.by
          password: b8%sdf_KD12
          subject: Github Actions job result
          # Literal body:
          body: Build job of ${{github.repository}} completed successfully!
          to: alexeyfeoktistoff1@gmail.com
          from: Luke Skywalker # <user@example.com>
          # Optional content type (defaults to text/plain):
          content_type: text/html
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional attachments:
#          attachments: build/app/outputs/flutter-apk/app-release.apk