# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: TestWorkflow

on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "8.x"

      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - run: flutter pub get
      
      - run: flutter build apk --release
      
      - uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.yandex.ru
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          # Literal body:
          body: Build job of ${{github.repository}} completed successfully!
          to: alexeyfeoktistoff1@gmail.com
          from: Luke Skywalker # <user@example.com>
          # Optional content type (defaults to text/plain):
          content_type: text/html
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional attachments:
          attachments: build/app/outputs/flutter-apk/app-release.apk